[[aws_c_auth]]
arch = "aarch64"
git-tree-sha1 = "52f5f2920a56e894be7a21eaf08ab0156c487bd9"
os = "macos"

    [[aws_c_auth.download]]
    sha256 = "5f69bdb11bbab5fb1cc88acd79e74740c67eddc1420ec89b1e59ccb5a44980df"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.9.3+0/aws_c_auth.v0.9.3.aarch64-apple-darwin.tar.gz"
[[aws_c_auth]]
arch = "aarch64"
git-tree-sha1 = "4e4a997c1c7ed410adcdc182a6352e1ec9e44d84"
libc = "glibc"
os = "linux"

    [[aws_c_auth.download]]
    sha256 = "fadb33bb8072484f83c42815ebc5abc56e741685bf8e4abb58180037102ed199"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.9.3+0/aws_c_auth.v0.9.3.aarch64-linux-gnu.tar.gz"
[[aws_c_auth]]
arch = "aarch64"
git-tree-sha1 = "fb8cccface873ae84751dfe7a7fc74821e558e8c"
libc = "musl"
os = "linux"

    [[aws_c_auth.download]]
    sha256 = "ef4a5723d442a83e799ee19745f954091b2d18581171f684e8b8d46f0938bd54"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.9.3+0/aws_c_auth.v0.9.3.aarch64-linux-musl.tar.gz"
[[aws_c_auth]]
arch = "aarch64"
git-tree-sha1 = "c094c242be191bb162ac24c36adfb562147ac211"
os = "freebsd"

    [[aws_c_auth.download]]
    sha256 = "b4dda79e2dd131f66975fa4d71b78150e593434df5d21cadcaeb78386e65b4cb"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.9.3+0/aws_c_auth.v0.9.3.aarch64-unknown-freebsd.tar.gz"
[[aws_c_auth]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6d44a888235a26a459bd9bc70116714893924960"
libc = "glibc"
os = "linux"

    [[aws_c_auth.download]]
    sha256 = "a0c5eded62851579244eec7e518d3d64303e8e913c145d0add57c27e3c1fdb25"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.9.3+0/aws_c_auth.v0.9.3.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_auth]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "49a7481dc89eb8495c36781263b922af1c8bbb98"
libc = "musl"
os = "linux"

    [[aws_c_auth.download]]
    sha256 = "68355c8a27e39293e1e1588599ed9ec3f1aca3cc470340a84a4591299e81ed34"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.9.3+0/aws_c_auth.v0.9.3.armv6l-linux-musleabihf.tar.gz"
[[aws_c_auth]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6670f5d27378404919f31b6b567acf0768481355"
libc = "glibc"
os = "linux"

    [[aws_c_auth.download]]
    sha256 = "02d1d5633321b128949c3d40605dad24d6d3978d235cebd4cb3af0d51da9e41b"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.9.3+0/aws_c_auth.v0.9.3.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_auth]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f06d2108282cf9b22c5efb77f206e595ef7458bd"
libc = "musl"
os = "linux"

    [[aws_c_auth.download]]
    sha256 = "5ea46a66ea65f983bb7468c61690f377ab370f965a159c0638fdc8092513843c"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.9.3+0/aws_c_auth.v0.9.3.armv7l-linux-musleabihf.tar.gz"
[[aws_c_auth]]
arch = "i686"
git-tree-sha1 = "179f417400678a4783cd073c7c070bf4ffb23387"
libc = "glibc"
os = "linux"

    [[aws_c_auth.download]]
    sha256 = "a1d5708577fb43e5d4ff2cb36b0b7ef7b1f7db0aa3f80baabeafb40592fbccc7"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.9.3+0/aws_c_auth.v0.9.3.i686-linux-gnu.tar.gz"
[[aws_c_auth]]
arch = "i686"
git-tree-sha1 = "aaffa0e5725686c1d6f1d4301e2d6cc1532f587a"
libc = "musl"
os = "linux"

    [[aws_c_auth.download]]
    sha256 = "559ce895071be98b8e18ac349fd28d1ffe3b3d7af8c93b8022f52686bbe1ea14"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.9.3+0/aws_c_auth.v0.9.3.i686-linux-musl.tar.gz"
[[aws_c_auth]]
arch = "powerpc64le"
git-tree-sha1 = "3a6cddbde52a6da13162957a7ca861e252682016"
libc = "glibc"
os = "linux"

    [[aws_c_auth.download]]
    sha256 = "5cfee7918fee3bcc54481f0eaef798f156346655fed15950114d6ce695f54beb"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.9.3+0/aws_c_auth.v0.9.3.powerpc64le-linux-gnu.tar.gz"
[[aws_c_auth]]
arch = "riscv64"
git-tree-sha1 = "5574ba784eee32b7d9f66e554638d0669bc174a5"
libc = "glibc"
os = "linux"

    [[aws_c_auth.download]]
    sha256 = "ea1d2365f6f3fd981f48c15dbcc2bd85d46e39fb938d32b4a0d053c195732b23"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.9.3+0/aws_c_auth.v0.9.3.riscv64-linux-gnu.tar.gz"
[[aws_c_auth]]
arch = "x86_64"
git-tree-sha1 = "befd205a990c6686034fc2c7b9da95410d30f8ae"
os = "macos"

    [[aws_c_auth.download]]
    sha256 = "a64c0101546528619263da5131c931f1e661aeec0b53d1f17cb20ef4e86a60f7"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.9.3+0/aws_c_auth.v0.9.3.x86_64-apple-darwin.tar.gz"
[[aws_c_auth]]
arch = "x86_64"
git-tree-sha1 = "ec69dcb412c43a336e74b182b6d88bfbe33c1fbf"
libc = "glibc"
os = "linux"

    [[aws_c_auth.download]]
    sha256 = "20f99ac67af8cd487de89741922cb8ab693117d2bbe64c8ae8bd6ee0cef6d2b3"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.9.3+0/aws_c_auth.v0.9.3.x86_64-linux-gnu.tar.gz"
[[aws_c_auth]]
arch = "x86_64"
git-tree-sha1 = "95e448caef892c84505ff7e346374d2aaa3ad480"
libc = "musl"
os = "linux"

    [[aws_c_auth.download]]
    sha256 = "180f45849766c8cdb56daadf79631fce700d01ae47e15b7bab943f4163c9f750"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.9.3+0/aws_c_auth.v0.9.3.x86_64-linux-musl.tar.gz"
[[aws_c_auth]]
arch = "x86_64"
git-tree-sha1 = "b77efb56508e1c7c4897a604875fa99c1bf0c87a"
os = "freebsd"

    [[aws_c_auth.download]]
    sha256 = "05e8d18c257e3d05e3826154f0a541facf62eea89df2b995bd933ee50d6614cf"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.9.3+0/aws_c_auth.v0.9.3.x86_64-unknown-freebsd.tar.gz"
[[aws_c_auth]]
arch = "x86_64"
git-tree-sha1 = "ef6848b48982ec4b479dcb374131c09c35814a4e"
os = "windows"

    [[aws_c_auth.download]]
    sha256 = "dc30fb60cf98818aa0527ee73e5e69edc3e6d241d44a5877c1e1cce8c91f05be"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.9.3+0/aws_c_auth.v0.9.3.x86_64-w64-mingw32.tar.gz"
