[[aws_c_auth]]
arch = "aarch64"
git-tree-sha1 = "b930cafef554b6457c0174bd4d978b8da0fe17dc"
os = "macos"

    [[aws_c_auth.download]]
    sha256 = "df05552ea6a5c7a8df4e8b245e2b11421b23bf94e464278ff586d061845f62dc"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.10.0+0/aws_c_auth.v0.10.0.aarch64-apple-darwin.tar.gz"
[[aws_c_auth]]
arch = "aarch64"
git-tree-sha1 = "94fb2d9ed6312dbdd18ff53be4b831ab3a47b79b"
libc = "glibc"
os = "linux"

    [[aws_c_auth.download]]
    sha256 = "fc76034a0540514736f5c7299c928e9ee9242eae3333fb0303cf835a30b386e5"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.10.0+0/aws_c_auth.v0.10.0.aarch64-linux-gnu.tar.gz"
[[aws_c_auth]]
arch = "aarch64"
git-tree-sha1 = "14ef30bf179c6592812bafb0792f276e95837f45"
libc = "musl"
os = "linux"

    [[aws_c_auth.download]]
    sha256 = "349ec996638f00b924eeb3ecc59588c9b39647d10aa825e2331781153dfced04"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.10.0+0/aws_c_auth.v0.10.0.aarch64-linux-musl.tar.gz"
[[aws_c_auth]]
arch = "aarch64"
git-tree-sha1 = "d816e133b8aae3ff929390a2b426821c2ffd6a4e"
os = "freebsd"

    [[aws_c_auth.download]]
    sha256 = "a729feeb51dc2041fd931dcb11dfbd2fddf91011f00e4b122e372c54b6e1a316"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.10.0+0/aws_c_auth.v0.10.0.aarch64-unknown-freebsd.tar.gz"
[[aws_c_auth]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "94452d6c5186ff0776e6581d352a0a1fcff7c0a5"
libc = "glibc"
os = "linux"

    [[aws_c_auth.download]]
    sha256 = "ce62daded0e208c3dbff980bb9e13810c8423ec6f075707625cb7a3cdb601eee"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.10.0+0/aws_c_auth.v0.10.0.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_auth]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "377216fa555727478db28123db292cd9be24f3c8"
libc = "musl"
os = "linux"

    [[aws_c_auth.download]]
    sha256 = "d8488da63311e012c825db72badf4136098d277ec729178bfc6d1763a3e4bed7"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.10.0+0/aws_c_auth.v0.10.0.armv6l-linux-musleabihf.tar.gz"
[[aws_c_auth]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "248c70db19887551f008a4b2a7ee6e286be982d7"
libc = "glibc"
os = "linux"

    [[aws_c_auth.download]]
    sha256 = "124ce5beaa9ddb76a62688bc325d42635a3c3a8ee7d9d690a2f905f1149f7822"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.10.0+0/aws_c_auth.v0.10.0.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_auth]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "102fa69b59a2c7f247404ed7d8a2a23f072d0ea0"
libc = "musl"
os = "linux"

    [[aws_c_auth.download]]
    sha256 = "8ecba53a040aaf8f67a003fcccf257c17219fb9cf0101b89e6f700f1745ed1a5"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.10.0+0/aws_c_auth.v0.10.0.armv7l-linux-musleabihf.tar.gz"
[[aws_c_auth]]
arch = "i686"
git-tree-sha1 = "1ea3bea9beeda9d449c8b0b064f71d75a5699518"
libc = "glibc"
os = "linux"

    [[aws_c_auth.download]]
    sha256 = "b039632410de9ce636f56b7c1e0107860786e71dc4b7180d089093c4a4c32cdd"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.10.0+0/aws_c_auth.v0.10.0.i686-linux-gnu.tar.gz"
[[aws_c_auth]]
arch = "i686"
git-tree-sha1 = "3059c94b1d38724c4c684053696787c8983913fe"
libc = "musl"
os = "linux"

    [[aws_c_auth.download]]
    sha256 = "e8f978021e29207c4b1cda73b6bae126de041acd89f13b92c3af31bb82f3253b"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.10.0+0/aws_c_auth.v0.10.0.i686-linux-musl.tar.gz"
[[aws_c_auth]]
arch = "powerpc64le"
git-tree-sha1 = "d6c93796946103012207cd4c434dd0736b4099ed"
libc = "glibc"
os = "linux"

    [[aws_c_auth.download]]
    sha256 = "3fc87cda19fc521c2f541d17ddc51d93e03941c8e8fa6050e904018acbcb4d2a"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.10.0+0/aws_c_auth.v0.10.0.powerpc64le-linux-gnu.tar.gz"
[[aws_c_auth]]
arch = "riscv64"
git-tree-sha1 = "2bdde86d65e12f786d73f6134f34fde69e05bb11"
libc = "glibc"
os = "linux"

    [[aws_c_auth.download]]
    sha256 = "3bedb2cc3c9535ba7f4361bb1c899d45d6492bfd2afef8cae6ec9873b30ca90d"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.10.0+0/aws_c_auth.v0.10.0.riscv64-linux-gnu.tar.gz"
[[aws_c_auth]]
arch = "x86_64"
git-tree-sha1 = "96aa0eddd1911c39df40648e6bc6b37dab1b8d34"
os = "macos"

    [[aws_c_auth.download]]
    sha256 = "6d0a1d50cef2e100f209df2edccb8705b85b6ce63d13086b6d52ce65fd163e7c"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.10.0+0/aws_c_auth.v0.10.0.x86_64-apple-darwin.tar.gz"
[[aws_c_auth]]
arch = "x86_64"
git-tree-sha1 = "660a83ff3ac0af2fd2eb1b6fcca3b3e94565f3b2"
libc = "glibc"
os = "linux"

    [[aws_c_auth.download]]
    sha256 = "ef06d9f018058ed5901a9d54fb3449bd8bb8d804cd5598202af66b118c094a34"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.10.0+0/aws_c_auth.v0.10.0.x86_64-linux-gnu.tar.gz"
[[aws_c_auth]]
arch = "x86_64"
git-tree-sha1 = "415e6b87ce469c671ffd10d2df7f7632ac75b79d"
libc = "musl"
os = "linux"

    [[aws_c_auth.download]]
    sha256 = "4bdbcf3022ea987a212eac3e0abc723004792731ec9e2549993e224dee4e0e67"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.10.0+0/aws_c_auth.v0.10.0.x86_64-linux-musl.tar.gz"
[[aws_c_auth]]
arch = "x86_64"
git-tree-sha1 = "7ce95c4a18aba8bb92020f3b39b497505a213291"
os = "freebsd"

    [[aws_c_auth.download]]
    sha256 = "e08d4fc19cca51c6f428025dfdd90f10a03a4a9a49514b03f0c8b0eafcde8d8e"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.10.0+0/aws_c_auth.v0.10.0.x86_64-unknown-freebsd.tar.gz"
[[aws_c_auth]]
arch = "x86_64"
git-tree-sha1 = "22324d4d70f8ba2abfeba58efb4a8b511e413b07"
os = "windows"

    [[aws_c_auth.download]]
    sha256 = "4a8153e7b40c11f7a71fd5683fb7d4a20a7c23ad24031fae7a15cee4ddc69494"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.10.0+0/aws_c_auth.v0.10.0.x86_64-w64-mingw32.tar.gz"
