[[aws_c_auth]]
arch = "aarch64"
git-tree-sha1 = "7be6f4551f1322db2a930334d93f0691aeec70b9"
os = "macos"

    [[aws_c_auth.download]]
    sha256 = "437184fa6d10f9191a83b48d51a8e51825ff20a23d7afdf8416a973d789dccff"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.9.4+0/aws_c_auth.v0.9.4.aarch64-apple-darwin.tar.gz"
[[aws_c_auth]]
arch = "aarch64"
git-tree-sha1 = "1a4d35a1d0f4103f1aedcf2fbb68efd6ae0ef814"
libc = "glibc"
os = "linux"

    [[aws_c_auth.download]]
    sha256 = "064776d0c2d6641248311dba30b5b9d4f49ca439a22a07f810f63697b91ca51e"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.9.4+0/aws_c_auth.v0.9.4.aarch64-linux-gnu.tar.gz"
[[aws_c_auth]]
arch = "aarch64"
git-tree-sha1 = "65225a603d77a7c834fe38a2097c97c19bab98ba"
libc = "musl"
os = "linux"

    [[aws_c_auth.download]]
    sha256 = "e49a1f69e327c909c0af3cf10a0aa946ac5fa959640ff2a6937851de92347c3e"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.9.4+0/aws_c_auth.v0.9.4.aarch64-linux-musl.tar.gz"
[[aws_c_auth]]
arch = "aarch64"
git-tree-sha1 = "484e8f198df910ddba097467052c34efaa78b810"
os = "freebsd"

    [[aws_c_auth.download]]
    sha256 = "ccb0711d4255f26d5064ef6acd219043480c56c73cf62f559180b257b73a5708"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.9.4+0/aws_c_auth.v0.9.4.aarch64-unknown-freebsd.tar.gz"
[[aws_c_auth]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8e43b3934f3787d9832f415bc28c92171da5e697"
libc = "glibc"
os = "linux"

    [[aws_c_auth.download]]
    sha256 = "172d23698b4e488b4177e9ba820fbeffc8c742fd7838925f72329f8b1e4d1454"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.9.4+0/aws_c_auth.v0.9.4.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_auth]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4eb3603ac9448fc69aaf6759e87ee113c75d06f9"
libc = "musl"
os = "linux"

    [[aws_c_auth.download]]
    sha256 = "372fa2cbb31e9bf427eb6eed36447f8e477fa9e15fc427cc8ddf31c703390aad"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.9.4+0/aws_c_auth.v0.9.4.armv6l-linux-musleabihf.tar.gz"
[[aws_c_auth]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8166a0efb0f2a6ceeb9edeacb52c39fb2b481239"
libc = "glibc"
os = "linux"

    [[aws_c_auth.download]]
    sha256 = "259ae280c676042d6647b9d0812b163ff119f431cfa2734bffb8b6ede1d253ad"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.9.4+0/aws_c_auth.v0.9.4.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_auth]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2f84596f5360aa7be48d0e4987bf5e8d3f18c562"
libc = "musl"
os = "linux"

    [[aws_c_auth.download]]
    sha256 = "b4d38ce928337d503a68d8266326ed4c43ac93372fcacdacb20bfb0a6751b347"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.9.4+0/aws_c_auth.v0.9.4.armv7l-linux-musleabihf.tar.gz"
[[aws_c_auth]]
arch = "i686"
git-tree-sha1 = "9c873beae3ff1cadc0457b1c819542c4b3374540"
libc = "glibc"
os = "linux"

    [[aws_c_auth.download]]
    sha256 = "eb3afd9006c151db720c96d79d8f2625a3c642f6bdcd1f269fa0a51b35f9def4"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.9.4+0/aws_c_auth.v0.9.4.i686-linux-gnu.tar.gz"
[[aws_c_auth]]
arch = "i686"
git-tree-sha1 = "044223f3f8e4d4d2acacbf98cb11d5ac2a1eb921"
libc = "musl"
os = "linux"

    [[aws_c_auth.download]]
    sha256 = "121d7492a8b87a383f4fc11fca0b046c7621aa014b7a277c6444df9c1e174f71"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.9.4+0/aws_c_auth.v0.9.4.i686-linux-musl.tar.gz"
[[aws_c_auth]]
arch = "powerpc64le"
git-tree-sha1 = "3e28ddd9d71f42125547d415390d9a7334ea9e7d"
libc = "glibc"
os = "linux"

    [[aws_c_auth.download]]
    sha256 = "a0b4b641bc34b976c87bf30200c88ea0572def4151ca0dae0eb423f304bd4342"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.9.4+0/aws_c_auth.v0.9.4.powerpc64le-linux-gnu.tar.gz"
[[aws_c_auth]]
arch = "riscv64"
git-tree-sha1 = "5276e8e2b97c45c9b3a055194b81d76cc2743476"
libc = "glibc"
os = "linux"

    [[aws_c_auth.download]]
    sha256 = "abf222ec233763c870e525a92ea609ddf2d190a9b4afedc96de782b89d559a6f"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.9.4+0/aws_c_auth.v0.9.4.riscv64-linux-gnu.tar.gz"
[[aws_c_auth]]
arch = "x86_64"
git-tree-sha1 = "ac07bae74503e2d5dc15ea4ddd0198cd8624a6b1"
os = "macos"

    [[aws_c_auth.download]]
    sha256 = "f860219c63188368dda2c41c17d50663b37a9d2b4b9a2dd9c0fcd51b2a689706"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.9.4+0/aws_c_auth.v0.9.4.x86_64-apple-darwin.tar.gz"
[[aws_c_auth]]
arch = "x86_64"
git-tree-sha1 = "466f255de3ebd2bb1fe7d4bbb1b43995dd14314b"
libc = "glibc"
os = "linux"

    [[aws_c_auth.download]]
    sha256 = "a71553cabe3b2fb120ca35cb7b6d57bc482c9f7f963be10803178523fc88fd8b"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.9.4+0/aws_c_auth.v0.9.4.x86_64-linux-gnu.tar.gz"
[[aws_c_auth]]
arch = "x86_64"
git-tree-sha1 = "55cdb5f4e0740075133a756cce3ca1ba38a59845"
libc = "musl"
os = "linux"

    [[aws_c_auth.download]]
    sha256 = "4dbcc4510d617073c7ad83ebc79728eb063d993c1115671c8810646be48f239a"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.9.4+0/aws_c_auth.v0.9.4.x86_64-linux-musl.tar.gz"
[[aws_c_auth]]
arch = "x86_64"
git-tree-sha1 = "ddf37043cb99aaaa444175171a855c784c33f47a"
os = "freebsd"

    [[aws_c_auth.download]]
    sha256 = "299fc5d3951a837c30e2f13dcef15b49f53eae070ca5c0835d376d483490d953"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.9.4+0/aws_c_auth.v0.9.4.x86_64-unknown-freebsd.tar.gz"
[[aws_c_auth]]
arch = "x86_64"
git-tree-sha1 = "fc404fb81ac7d666e9826c4bbf072a6b8ae2f3a3"
os = "windows"

    [[aws_c_auth.download]]
    sha256 = "9f1d9ef9835541aed198accb37320ea7272679aa95a603790308d9b2e3151d5a"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.9.4+0/aws_c_auth.v0.9.4.x86_64-w64-mingw32.tar.gz"
