[[aws_c_auth]]
arch = "aarch64"
git-tree-sha1 = "d39295b7e95dbad8a0ddd1068671329e8a11dc4a"
os = "macos"

    [[aws_c_auth.download]]
    sha256 = "9861a5af7a4f45bd3c061f520d75e9da37ae78ea9621232c1ecf1ab6af8727af"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.9.5+0/aws_c_auth.v0.9.5.aarch64-apple-darwin.tar.gz"
[[aws_c_auth]]
arch = "aarch64"
git-tree-sha1 = "1e07db4b4f7b57678ed22a32f4a41c0913667ffa"
libc = "glibc"
os = "linux"

    [[aws_c_auth.download]]
    sha256 = "094150de5977fd803275072e136866f0cdc535a3a913acfb9b5a3e498e9c8f73"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.9.5+0/aws_c_auth.v0.9.5.aarch64-linux-gnu.tar.gz"
[[aws_c_auth]]
arch = "aarch64"
git-tree-sha1 = "e634c8d243a3055cb5f0b9a2855cf9fcbaaf4612"
libc = "musl"
os = "linux"

    [[aws_c_auth.download]]
    sha256 = "18f5168cbf15a5702cfc00b8eabd58f7bbe26ad7cbf131c1df489a37bf83ebcf"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.9.5+0/aws_c_auth.v0.9.5.aarch64-linux-musl.tar.gz"
[[aws_c_auth]]
arch = "aarch64"
git-tree-sha1 = "01bfdf4efd97725d39b03e3202a85e5fe2d9ce40"
os = "freebsd"

    [[aws_c_auth.download]]
    sha256 = "48226467aaea52ec96cefaf1d5d308c7cb60a23b43005df76bb78286400e95eb"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.9.5+0/aws_c_auth.v0.9.5.aarch64-unknown-freebsd.tar.gz"
[[aws_c_auth]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "dbe219fec3f82b534ff114298604ef4c4991d5ca"
libc = "glibc"
os = "linux"

    [[aws_c_auth.download]]
    sha256 = "47cf9f3c753b8947cf41c7e509ef488ca3e3b3c469e8bd1a396c454b1dc0d3db"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.9.5+0/aws_c_auth.v0.9.5.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_auth]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "85a150938fa91a7e12a3d0788ac3a17388532d85"
libc = "musl"
os = "linux"

    [[aws_c_auth.download]]
    sha256 = "65056dab5cd3cf5ed5084e3e329409325c97c06cce931c784ca54fe90a485cdf"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.9.5+0/aws_c_auth.v0.9.5.armv6l-linux-musleabihf.tar.gz"
[[aws_c_auth]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2f5d8bdfc06c4e284f46695503b4be4dc62480b1"
libc = "glibc"
os = "linux"

    [[aws_c_auth.download]]
    sha256 = "0e0ef64cebc7df3ee05c05802166eeae6e41c6a30868529b271afa0b11e9bc0c"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.9.5+0/aws_c_auth.v0.9.5.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_auth]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b8a737f2cabd5167d0ea8f4dee129946c8cae464"
libc = "musl"
os = "linux"

    [[aws_c_auth.download]]
    sha256 = "6191fcecb0fa15c8ceb3eb6a11c6997f77463bf1bfa41cf38f43a30fba4162e3"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.9.5+0/aws_c_auth.v0.9.5.armv7l-linux-musleabihf.tar.gz"
[[aws_c_auth]]
arch = "i686"
git-tree-sha1 = "9a197dbced4322975829ec47a5e00c1b3ec7b38d"
libc = "glibc"
os = "linux"

    [[aws_c_auth.download]]
    sha256 = "96629ca5e0128909f21e9af6cd384b68f13aa6e2681b3d4e64a8fa5bd67662fe"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.9.5+0/aws_c_auth.v0.9.5.i686-linux-gnu.tar.gz"
[[aws_c_auth]]
arch = "i686"
git-tree-sha1 = "c8b634520649156a487050109bb82c8c65c77428"
libc = "musl"
os = "linux"

    [[aws_c_auth.download]]
    sha256 = "0cd39485615ecd738b0ae459e52a9839188fb53d49e98b8a3f8d284a6409d6f5"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.9.5+0/aws_c_auth.v0.9.5.i686-linux-musl.tar.gz"
[[aws_c_auth]]
arch = "powerpc64le"
git-tree-sha1 = "c793b43040aabf6b2c2b48c8faea745b5e432c11"
libc = "glibc"
os = "linux"

    [[aws_c_auth.download]]
    sha256 = "4cca948c7bea549fbfe6afe66020444f751edbfbd19e92d896c77ea2c7a46ea0"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.9.5+0/aws_c_auth.v0.9.5.powerpc64le-linux-gnu.tar.gz"
[[aws_c_auth]]
arch = "riscv64"
git-tree-sha1 = "8b3ce3910d1227301927566d2312e8a93d87fc61"
libc = "glibc"
os = "linux"

    [[aws_c_auth.download]]
    sha256 = "7bec1b02034859d913ca54a9c606d26a53831cd541f1d318b5dc9b438f68ac6f"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.9.5+0/aws_c_auth.v0.9.5.riscv64-linux-gnu.tar.gz"
[[aws_c_auth]]
arch = "x86_64"
git-tree-sha1 = "069af76b8593e5e904b764abf015742a71bcbe61"
os = "macos"

    [[aws_c_auth.download]]
    sha256 = "60da88ea4a1a4d03f6edad4f90c6407546d03e88e1d955269e21d4f6e253cf72"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.9.5+0/aws_c_auth.v0.9.5.x86_64-apple-darwin.tar.gz"
[[aws_c_auth]]
arch = "x86_64"
git-tree-sha1 = "2870a66510674e9195e0e7282a4ebb928dea82a3"
libc = "glibc"
os = "linux"

    [[aws_c_auth.download]]
    sha256 = "1eb462fc49cdee90ce45ecbbf4ff6eac2400825972ef18db3648d2a48163825c"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.9.5+0/aws_c_auth.v0.9.5.x86_64-linux-gnu.tar.gz"
[[aws_c_auth]]
arch = "x86_64"
git-tree-sha1 = "296341759b2385b07fdc97d825221bb0471cf1b6"
libc = "musl"
os = "linux"

    [[aws_c_auth.download]]
    sha256 = "dc5937b022dbdba3185f82f4d85b3c9a7dce1228d8fa991b25336317e2f7ef26"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.9.5+0/aws_c_auth.v0.9.5.x86_64-linux-musl.tar.gz"
[[aws_c_auth]]
arch = "x86_64"
git-tree-sha1 = "e70f35cf17dfc9a354fbb1ee92db60db2a3954d2"
os = "freebsd"

    [[aws_c_auth.download]]
    sha256 = "36fbfdebbf7f34ae18519562bc8e61094c110c52e8869cb31ab850f459f6c3f4"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.9.5+0/aws_c_auth.v0.9.5.x86_64-unknown-freebsd.tar.gz"
[[aws_c_auth]]
arch = "x86_64"
git-tree-sha1 = "18fce0bb8533b3082e4abb1ea2e97d987e25565d"
os = "windows"

    [[aws_c_auth.download]]
    sha256 = "9c936cc66f17c8e7fc0f8bbf0fbca23a367f5a4ab54d1af5ce9be2e737f6f36e"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_auth_jll.jl/releases/download/aws_c_auth-v0.9.5+0/aws_c_auth.v0.9.5.x86_64-w64-mingw32.tar.gz"
